# Generated by Django 2.2.1 on 2019-06-27 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_cadastro',
            field=models.DateField(null=True),
        ),
    ]
